[package]
name = "hi_ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
hi_core = { path = "../hi_core" }
libc = "0.2.169"
toml = "0.8.19"
serde = { version = "1.0.216", features = ["derive"] }

[build-dependencies]
cbindgen = "0.29.2"
