[package]
name = "hcore_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
directories = "5.0"
colored = "2.0"
thiserror = "1.0"
lazy_static = "1.4"
